package com.lx.benefits.bean.entity.agent;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class AgentRebateDeployExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    public AgentRebateDeployExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andManagementFeeRatioIsNull() {
            addCriterion("management_fee_ratio is null");
            return (Criteria) this;
        }

        public Criteria andManagementFeeRatioIsNotNull() {
            addCriterion("management_fee_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andManagementFeeRatioEqualTo(BigDecimal value) {
            addCriterion("management_fee_ratio =", value, "managementFeeRatio");
            return (Criteria) this;
        }

        public Criteria andManagementFeeRatioNotEqualTo(BigDecimal value) {
            addCriterion("management_fee_ratio <>", value, "managementFeeRatio");
            return (Criteria) this;
        }

        public Criteria andManagementFeeRatioGreaterThan(BigDecimal value) {
            addCriterion("management_fee_ratio >", value, "managementFeeRatio");
            return (Criteria) this;
        }

        public Criteria andManagementFeeRatioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("management_fee_ratio >=", value, "managementFeeRatio");
            return (Criteria) this;
        }

        public Criteria andManagementFeeRatioLessThan(BigDecimal value) {
            addCriterion("management_fee_ratio <", value, "managementFeeRatio");
            return (Criteria) this;
        }

        public Criteria andManagementFeeRatioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("management_fee_ratio <=", value, "managementFeeRatio");
            return (Criteria) this;
        }

        public Criteria andManagementFeeRatioIn(List<BigDecimal> values) {
            addCriterion("management_fee_ratio in", values, "managementFeeRatio");
            return (Criteria) this;
        }

        public Criteria andManagementFeeRatioNotIn(List<BigDecimal> values) {
            addCriterion("management_fee_ratio not in", values, "managementFeeRatio");
            return (Criteria) this;
        }

        public Criteria andManagementFeeRatioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("management_fee_ratio between", value1, value2, "managementFeeRatio");
            return (Criteria) this;
        }

        public Criteria andManagementFeeRatioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("management_fee_ratio not between", value1, value2, "managementFeeRatio");
            return (Criteria) this;
        }

        public Criteria andMatterTaxIsNull() {
            addCriterion("matter_tax is null");
            return (Criteria) this;
        }

        public Criteria andMatterTaxIsNotNull() {
            addCriterion("matter_tax is not null");
            return (Criteria) this;
        }

        public Criteria andMatterTaxEqualTo(BigDecimal value) {
            addCriterion("matter_tax =", value, "matterTax");
            return (Criteria) this;
        }

        public Criteria andMatterTaxNotEqualTo(BigDecimal value) {
            addCriterion("matter_tax <>", value, "matterTax");
            return (Criteria) this;
        }

        public Criteria andMatterTaxGreaterThan(BigDecimal value) {
            addCriterion("matter_tax >", value, "matterTax");
            return (Criteria) this;
        }

        public Criteria andMatterTaxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("matter_tax >=", value, "matterTax");
            return (Criteria) this;
        }

        public Criteria andMatterTaxLessThan(BigDecimal value) {
            addCriterion("matter_tax <", value, "matterTax");
            return (Criteria) this;
        }

        public Criteria andMatterTaxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("matter_tax <=", value, "matterTax");
            return (Criteria) this;
        }

        public Criteria andMatterTaxIn(List<BigDecimal> values) {
            addCriterion("matter_tax in", values, "matterTax");
            return (Criteria) this;
        }

        public Criteria andMatterTaxNotIn(List<BigDecimal> values) {
            addCriterion("matter_tax not in", values, "matterTax");
            return (Criteria) this;
        }

        public Criteria andMatterTaxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("matter_tax between", value1, value2, "matterTax");
            return (Criteria) this;
        }

        public Criteria andMatterTaxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("matter_tax not between", value1, value2, "matterTax");
            return (Criteria) this;
        }

        public Criteria andVirtualTaxIsNull() {
            addCriterion("virtual_tax is null");
            return (Criteria) this;
        }

        public Criteria andVirtualTaxIsNotNull() {
            addCriterion("virtual_tax is not null");
            return (Criteria) this;
        }

        public Criteria andVirtualTaxEqualTo(BigDecimal value) {
            addCriterion("virtual_tax =", value, "virtualTax");
            return (Criteria) this;
        }

        public Criteria andVirtualTaxNotEqualTo(BigDecimal value) {
            addCriterion("virtual_tax <>", value, "virtualTax");
            return (Criteria) this;
        }

        public Criteria andVirtualTaxGreaterThan(BigDecimal value) {
            addCriterion("virtual_tax >", value, "virtualTax");
            return (Criteria) this;
        }

        public Criteria andVirtualTaxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("virtual_tax >=", value, "virtualTax");
            return (Criteria) this;
        }

        public Criteria andVirtualTaxLessThan(BigDecimal value) {
            addCriterion("virtual_tax <", value, "virtualTax");
            return (Criteria) this;
        }

        public Criteria andVirtualTaxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("virtual_tax <=", value, "virtualTax");
            return (Criteria) this;
        }

        public Criteria andVirtualTaxIn(List<BigDecimal> values) {
            addCriterion("virtual_tax in", values, "virtualTax");
            return (Criteria) this;
        }

        public Criteria andVirtualTaxNotIn(List<BigDecimal> values) {
            addCriterion("virtual_tax not in", values, "virtualTax");
            return (Criteria) this;
        }

        public Criteria andVirtualTaxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("virtual_tax between", value1, value2, "virtualTax");
            return (Criteria) this;
        }

        public Criteria andVirtualTaxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("virtual_tax not between", value1, value2, "virtualTax");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
