package com.lx.benefits.bean.entity.agent;

import java.io.Serializable;
import java.math.BigDecimal;

public class AgentRebateDeploy implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_rebate_deploy.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_rebate_deploy.management_fee_ratio
     *
     * @mbggenerated
     */
    private BigDecimal managementFeeRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_rebate_deploy.matter_tax
     *
     * @mbggenerated
     */
    private BigDecimal matterTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_rebate_deploy.virtual_tax
     *
     * @mbggenerated
     */
    private BigDecimal virtualTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_rebate_deploy.id
     *
     * @return the value of agent_rebate_deploy.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_rebate_deploy.id
     *
     * @param id the value for agent_rebate_deploy.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_rebate_deploy.management_fee_ratio
     *
     * @return the value of agent_rebate_deploy.management_fee_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getManagementFeeRatio() {
        return managementFeeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_rebate_deploy.management_fee_ratio
     *
     * @param managementFeeRatio the value for agent_rebate_deploy.management_fee_ratio
     *
     * @mbggenerated
     */
    public void setManagementFeeRatio(BigDecimal managementFeeRatio) {
        this.managementFeeRatio = managementFeeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_rebate_deploy.matter_tax
     *
     * @return the value of agent_rebate_deploy.matter_tax
     *
     * @mbggenerated
     */
    public BigDecimal getMatterTax() {
        return matterTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_rebate_deploy.matter_tax
     *
     * @param matterTax the value for agent_rebate_deploy.matter_tax
     *
     * @mbggenerated
     */
    public void setMatterTax(BigDecimal matterTax) {
        this.matterTax = matterTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_rebate_deploy.virtual_tax
     *
     * @return the value of agent_rebate_deploy.virtual_tax
     *
     * @mbggenerated
     */
    public BigDecimal getVirtualTax() {
        return virtualTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_rebate_deploy.virtual_tax
     *
     * @param virtualTax the value for agent_rebate_deploy.virtual_tax
     *
     * @mbggenerated
     */
    public void setVirtualTax(BigDecimal virtualTax) {
        this.virtualTax = virtualTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AgentRebateDeploy other = (AgentRebateDeploy) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getManagementFeeRatio() == null ? other.getManagementFeeRatio() == null : this.getManagementFeeRatio().equals(other.getManagementFeeRatio()))
            && (this.getMatterTax() == null ? other.getMatterTax() == null : this.getMatterTax().equals(other.getMatterTax()))
            && (this.getVirtualTax() == null ? other.getVirtualTax() == null : this.getVirtualTax().equals(other.getVirtualTax()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getManagementFeeRatio() == null) ? 0 : getManagementFeeRatio().hashCode());
        result = prime * result + ((getMatterTax() == null) ? 0 : getMatterTax().hashCode());
        result = prime * result + ((getVirtualTax() == null) ? 0 : getVirtualTax().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", managementFeeRatio=").append(managementFeeRatio);
        sb.append(", matterTax=").append(matterTax);
        sb.append(", virtualTax=").append(virtualTax);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
