package com.lx.benefits.bean.entity.voucher;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class VoucherProductTemplate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher_product_template.template_id
     *
     * @mbggenerated
     */
    private Long templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher_product_template.template_name
     *
     * @mbggenerated
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher_product_template.product_range
     *
     * @mbggenerated
     */
    private Byte productRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher_product_template.product_items
     *
     * @mbggenerated
     */
    private String productItems;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher_product_template.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher_product_template.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voucher_product_template.deleted
     *
     * @mbggenerated
     */
    private Byte deleted;

    private String updater;

    private String categoryId1;

    private String categoryId2;

    private List<VoucherBrandInfo> voucherBrandInfos;

    private List<VoucherSpuInfo> voucherSpuInfos;

    public List<VoucherBrandInfo> getVoucherBrandInfos() {
        return voucherBrandInfos;
    }

    public void setVoucherBrandInfos(List<VoucherBrandInfo> voucherBrandInfos) {
        this.voucherBrandInfos = voucherBrandInfos;
    }

    public List<VoucherSpuInfo> getVoucherSpuInfos() {
        return voucherSpuInfos;
    }

    public void setVoucherSpuInfos(List<VoucherSpuInfo> voucherSpuInfos) {
        this.voucherSpuInfos = voucherSpuInfos;
    }

    public String getCategoryId1() {
        return categoryId1;
    }

    public void setCategoryId1(String categoryId1) {
        this.categoryId1 = categoryId1;
    }

    public String getCategoryId2() {
        return categoryId2;
    }

    public void setCategoryId2(String categoryId2) {
        this.categoryId2 = categoryId2;
    }

    public String getUpdater() {
        return updater;
    }

    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voucher_product_template
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_product_template.template_id
     *
     * @return the value of voucher_product_template.template_id
     *
     * @mbggenerated
     */
    public Long getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_product_template.template_id
     *
     * @param templateId the value for voucher_product_template.template_id
     *
     * @mbggenerated
     */
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_product_template.template_name
     *
     * @return the value of voucher_product_template.template_name
     *
     * @mbggenerated
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_product_template.template_name
     *
     * @param templateName the value for voucher_product_template.template_name
     *
     * @mbggenerated
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_product_template.product_range
     *
     * @return the value of voucher_product_template.product_range
     *
     * @mbggenerated
     */
    public Byte getProductRange() {
        return productRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_product_template.product_range
     *
     * @param productRange the value for voucher_product_template.product_range
     *
     * @mbggenerated
     */
    public void setProductRange(Byte productRange) {
        this.productRange = productRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_product_template.product_items
     *
     * @return the value of voucher_product_template.product_items
     *
     * @mbggenerated
     */
    public String getProductItems() {
        return productItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_product_template.product_items
     *
     * @param productItems the value for voucher_product_template.product_items
     *
     * @mbggenerated
     */
    public void setProductItems(String productItems) {
        this.productItems = productItems == null ? null : productItems.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_product_template.create_time
     *
     * @return the value of voucher_product_template.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_product_template.create_time
     *
     * @param createTime the value for voucher_product_template.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_product_template.update_time
     *
     * @return the value of voucher_product_template.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_product_template.update_time
     *
     * @param updateTime the value for voucher_product_template.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_product_template.deleted
     *
     * @return the value of voucher_product_template.deleted
     *
     * @mbggenerated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_product_template.deleted
     *
     * @param deleted the value for voucher_product_template.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher_product_template
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VoucherProductTemplate other = (VoucherProductTemplate) that;
        return (this.getTemplateId() == null ? other.getTemplateId() == null : this.getTemplateId().equals(other.getTemplateId()))
            && (this.getTemplateName() == null ? other.getTemplateName() == null : this.getTemplateName().equals(other.getTemplateName()))
            && (this.getProductRange() == null ? other.getProductRange() == null : this.getProductRange().equals(other.getProductRange()))
            && (this.getProductItems() == null ? other.getProductItems() == null : this.getProductItems().equals(other.getProductItems()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher_product_template
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTemplateId() == null) ? 0 : getTemplateId().hashCode());
        result = prime * result + ((getTemplateName() == null) ? 0 : getTemplateName().hashCode());
        result = prime * result + ((getProductRange() == null) ? 0 : getProductRange().hashCode());
        result = prime * result + ((getProductItems() == null) ? 0 : getProductItems().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher_product_template
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", templateId=").append(templateId);
        sb.append(", templateName=").append(templateName);
        sb.append(", productRange=").append(productRange);
        sb.append(", productItems=").append(productItems);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
