package com.lx.benefits.bean.entity.voucher;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VoucherExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voucher
     *
     * @mbggenerated
     */
    protected String orderByClause;

    private Integer offset;

    private Integer limit;


    public Integer getOffset() {
        return offset;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voucher
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voucher
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    public VoucherExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voucher
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVoucherIdIsNull() {
            addCriterion("voucher_id is null");
            return (Criteria) this;
        }

        public Criteria andVoucherIdIsNotNull() {
            addCriterion("voucher_id is not null");
            return (Criteria) this;
        }

        public Criteria andVoucherIdEqualTo(Long value) {
            addCriterion("voucher_id =", value, "voucherId");
            return (Criteria) this;
        }

        public Criteria andVoucherStatusEqualTo(Integer value) {
            addCriterion("voucher_status =", value, "voucherStatus");
            return (Criteria) this;
        }

        public Criteria andVoucherTypeEqualTo(Integer value) {
            addCriterion("voucher_type =", value, "voucherType");
            return (Criteria) this;
        }

        public Criteria andVoucherIdNotEqualTo(Long value) {
            addCriterion("voucher_id <>", value, "voucherId");
            return (Criteria) this;
        }

        public Criteria andVoucherIdGreaterThan(Long value) {
            addCriterion("voucher_id >", value, "voucherId");
            return (Criteria) this;
        }

        public Criteria andVoucherIdGreaterThanOrEqualTo(Long value) {
            addCriterion("voucher_id >=", value, "voucherId");
            return (Criteria) this;
        }

        public Criteria andVoucherIdLessThan(Long value) {
            addCriterion("voucher_id <", value, "voucherId");
            return (Criteria) this;
        }

        public Criteria andVoucherIdLessThanOrEqualTo(Long value) {
            addCriterion("voucher_id <=", value, "voucherId");
            return (Criteria) this;
        }

        public Criteria andVoucherIdIn(List<Long> values) {
            addCriterion("voucher_id in", values, "voucherId");
            return (Criteria) this;
        }

        public Criteria andVoucherIdNotIn(List<Long> values) {
            addCriterion("voucher_id not in", values, "voucherId");
            return (Criteria) this;
        }

        public Criteria andVoucherIdBetween(Long value1, Long value2) {
            addCriterion("voucher_id between", value1, value2, "voucherId");
            return (Criteria) this;
        }

        public Criteria andVoucherIdNotBetween(Long value1, Long value2) {
            addCriterion("voucher_id not between", value1, value2, "voucherId");
            return (Criteria) this;
        }

        public Criteria andVoucherNameIsNull() {
            addCriterion("voucher_name is null");
            return (Criteria) this;
        }

        public Criteria andVoucherNameIsNotNull() {
            addCriterion("voucher_name is not null");
            return (Criteria) this;
        }

        public Criteria andVoucherNameEqualTo(String value) {
            addCriterion("voucher_name =", value, "voucherName");
            return (Criteria) this;
        }

        public Criteria andVoucherNameNotEqualTo(String value) {
            addCriterion("voucher_name <>", value, "voucherName");
            return (Criteria) this;
        }

        public Criteria andVoucherNameGreaterThan(String value) {
            addCriterion("voucher_name >", value, "voucherName");
            return (Criteria) this;
        }

        public Criteria andVoucherNameGreaterThanOrEqualTo(String value) {
            addCriterion("voucher_name >=", value, "voucherName");
            return (Criteria) this;
        }

        public Criteria andVoucherNameLessThan(String value) {
            addCriterion("voucher_name <", value, "voucherName");
            return (Criteria) this;
        }

        public Criteria andVoucherNameLessThanOrEqualTo(String value) {
            addCriterion("voucher_name <=", value, "voucherName");
            return (Criteria) this;
        }

        public Criteria andVoucherNameLike(String value) {
            addCriterion("voucher_name like", value, "voucherName");
            return (Criteria) this;
        }

        public Criteria andVoucherNameNotLike(String value) {
            addCriterion("voucher_name not like", value, "voucherName");
            return (Criteria) this;
        }

        public Criteria andVoucherNameIn(List<String> values) {
            addCriterion("voucher_name in", values, "voucherName");
            return (Criteria) this;
        }

        public Criteria andVoucherNameNotIn(List<String> values) {
            addCriterion("voucher_name not in", values, "voucherName");
            return (Criteria) this;
        }

        public Criteria andVoucherNameBetween(String value1, String value2) {
            addCriterion("voucher_name between", value1, value2, "voucherName");
            return (Criteria) this;
        }

        public Criteria andVoucherNameNotBetween(String value1, String value2) {
            addCriterion("voucher_name not between", value1, value2, "voucherName");
            return (Criteria) this;
        }

        public Criteria andTotalReleaseIsNull() {
            addCriterion("total_release is null");
            return (Criteria) this;
        }

        public Criteria andTotalReleaseIsNotNull() {
            addCriterion("total_release is not null");
            return (Criteria) this;
        }

        public Criteria andTotalReleaseEqualTo(Integer value) {
            addCriterion("total_release =", value, "totalRelease");
            return (Criteria) this;
        }

        public Criteria andTotalReleaseNotEqualTo(Integer value) {
            addCriterion("total_release <>", value, "totalRelease");
            return (Criteria) this;
        }

        public Criteria andTotalReleaseGreaterThan(Integer value) {
            addCriterion("total_release >", value, "totalRelease");
            return (Criteria) this;
        }

        public Criteria andTotalReleaseGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_release >=", value, "totalRelease");
            return (Criteria) this;
        }

        public Criteria andTotalReleaseLessThan(Integer value) {
            addCriterion("total_release <", value, "totalRelease");
            return (Criteria) this;
        }

        public Criteria andTotalReleaseLessThanOrEqualTo(Integer value) {
            addCriterion("total_release <=", value, "totalRelease");
            return (Criteria) this;
        }

        public Criteria andTotalReleaseIn(List<Integer> values) {
            addCriterion("total_release in", values, "totalRelease");
            return (Criteria) this;
        }

        public Criteria andTotalReleaseNotIn(List<Integer> values) {
            addCriterion("total_release not in", values, "totalRelease");
            return (Criteria) this;
        }

        public Criteria andTotalReleaseBetween(Integer value1, Integer value2) {
            addCriterion("total_release between", value1, value2, "totalRelease");
            return (Criteria) this;
        }

        public Criteria andTotalReleaseNotBetween(Integer value1, Integer value2) {
            addCriterion("total_release not between", value1, value2, "totalRelease");
            return (Criteria) this;
        }

        public Criteria andUseCaseIsNull() {
            addCriterion("use_case is null");
            return (Criteria) this;
        }

        public Criteria andUseCaseIsNotNull() {
            addCriterion("use_case is not null");
            return (Criteria) this;
        }

        public Criteria andUseCaseEqualTo(Integer value) {
            addCriterion("use_case =", value, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseNotEqualTo(Integer value) {
            addCriterion("use_case <>", value, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseGreaterThan(Integer value) {
            addCriterion("use_case >", value, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseGreaterThanOrEqualTo(Integer value) {
            addCriterion("use_case >=", value, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseLessThan(Integer value) {
            addCriterion("use_case <", value, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseLessThanOrEqualTo(Integer value) {
            addCriterion("use_case <=", value, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseIn(List<Integer> values) {
            addCriterion("use_case in", values, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseNotIn(List<Integer> values) {
            addCriterion("use_case not in", values, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseBetween(Integer value1, Integer value2) {
            addCriterion("use_case between", value1, value2, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseNotBetween(Integer value1, Integer value2) {
            addCriterion("use_case not between", value1, value2, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseThresholdIsNull() {
            addCriterion("use_threshold is null");
            return (Criteria) this;
        }

        public Criteria andUseThresholdIsNotNull() {
            addCriterion("use_threshold is not null");
            return (Criteria) this;
        }

        public Criteria andUseThresholdEqualTo(Integer value) {
            addCriterion("use_threshold =", value, "useThreshold");
            return (Criteria) this;
        }

        public Criteria andUseThresholdNotEqualTo(Integer value) {
            addCriterion("use_threshold <>", value, "useThreshold");
            return (Criteria) this;
        }

        public Criteria andUseThresholdGreaterThan(Integer value) {
            addCriterion("use_threshold >", value, "useThreshold");
            return (Criteria) this;
        }

        public Criteria andUseThresholdGreaterThanOrEqualTo(Integer value) {
            addCriterion("use_threshold >=", value, "useThreshold");
            return (Criteria) this;
        }

        public Criteria andUseThresholdLessThan(Integer value) {
            addCriterion("use_threshold <", value, "useThreshold");
            return (Criteria) this;
        }

        public Criteria andUseThresholdLessThanOrEqualTo(Integer value) {
            addCriterion("use_threshold <=", value, "useThreshold");
            return (Criteria) this;
        }

        public Criteria andUseThresholdIn(List<Integer> values) {
            addCriterion("use_threshold in", values, "useThreshold");
            return (Criteria) this;
        }

        public Criteria andUseThresholdNotIn(List<Integer> values) {
            addCriterion("use_threshold not in", values, "useThreshold");
            return (Criteria) this;
        }

        public Criteria andUseThresholdBetween(Integer value1, Integer value2) {
            addCriterion("use_threshold between", value1, value2, "useThreshold");
            return (Criteria) this;
        }

        public Criteria andUseThresholdNotBetween(Integer value1, Integer value2) {
            addCriterion("use_threshold not between", value1, value2, "useThreshold");
            return (Criteria) this;
        }

        public Criteria andBenefitContentIsNull() {
            addCriterion("benefit_content is null");
            return (Criteria) this;
        }

        public Criteria andBenefitContentIsNotNull() {
            addCriterion("benefit_content is not null");
            return (Criteria) this;
        }

        public Criteria andBenefitContentEqualTo(Integer value) {
            addCriterion("benefit_content =", value, "benefitContent");
            return (Criteria) this;
        }

        public Criteria andBenefitContentNotEqualTo(Integer value) {
            addCriterion("benefit_content <>", value, "benefitContent");
            return (Criteria) this;
        }

        public Criteria andBenefitContentGreaterThan(Integer value) {
            addCriterion("benefit_content >", value, "benefitContent");
            return (Criteria) this;
        }

        public Criteria andBenefitContentGreaterThanOrEqualTo(Integer value) {
            addCriterion("benefit_content >=", value, "benefitContent");
            return (Criteria) this;
        }

        public Criteria andBenefitContentLessThan(Integer value) {
            addCriterion("benefit_content <", value, "benefitContent");
            return (Criteria) this;
        }

        public Criteria andBenefitContentLessThanOrEqualTo(Integer value) {
            addCriterion("benefit_content <=", value, "benefitContent");
            return (Criteria) this;
        }

        public Criteria andBenefitContentIn(List<Integer> values) {
            addCriterion("benefit_content in", values, "benefitContent");
            return (Criteria) this;
        }

        public Criteria andBenefitContentNotIn(List<Integer> values) {
            addCriterion("benefit_content not in", values, "benefitContent");
            return (Criteria) this;
        }

        public Criteria andBenefitContentBetween(Integer value1, Integer value2) {
            addCriterion("benefit_content between", value1, value2, "benefitContent");
            return (Criteria) this;
        }

        public Criteria andBenefitContentNotBetween(Integer value1, Integer value2) {
            addCriterion("benefit_content not between", value1, value2, "benefitContent");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeIsNull() {
            addCriterion("validate_start_time is null");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeIsNotNull() {
            addCriterion("validate_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeEqualTo(Date value) {
            addCriterion("validate_start_time =", value, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeNotEqualTo(Date value) {
            addCriterion("validate_start_time <>", value, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeGreaterThan(Date value) {
            addCriterion("validate_start_time >", value, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("validate_start_time >=", value, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeLessThan(Date value) {
            addCriterion("validate_start_time <", value, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("validate_start_time <=", value, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeIn(List<Date> values) {
            addCriterion("validate_start_time in", values, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeNotIn(List<Date> values) {
            addCriterion("validate_start_time not in", values, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeBetween(Date value1, Date value2) {
            addCriterion("validate_start_time between", value1, value2, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("validate_start_time not between", value1, value2, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeIsNull() {
            addCriterion("validate_end_time is null");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeIsNotNull() {
            addCriterion("validate_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeEqualTo(Date value) {
            addCriterion("validate_end_time =", value, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeNotEqualTo(Date value) {
            addCriterion("validate_end_time <>", value, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeGreaterThan(Date value) {
            addCriterion("validate_end_time >", value, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("validate_end_time >=", value, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeLessThan(Date value) {
            addCriterion("validate_end_time <", value, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("validate_end_time <=", value, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeIn(List<Date> values) {
            addCriterion("validate_end_time in", values, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeNotIn(List<Date> values) {
            addCriterion("validate_end_time not in", values, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeBetween(Date value1, Date value2) {
            addCriterion("validate_end_time between", value1, value2, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("validate_end_time not between", value1, value2, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andLimitNumIsNull() {
            addCriterion("limit_num is null");
            return (Criteria) this;
        }

        public Criteria andLimitNumIsNotNull() {
            addCriterion("limit_num is not null");
            return (Criteria) this;
        }

        public Criteria andLimitNumEqualTo(Integer value) {
            addCriterion("limit_num =", value, "limitNum");
            return (Criteria) this;
        }

        public Criteria andLimitNumNotEqualTo(Integer value) {
            addCriterion("limit_num <>", value, "limitNum");
            return (Criteria) this;
        }

        public Criteria andLimitNumGreaterThan(Integer value) {
            addCriterion("limit_num >", value, "limitNum");
            return (Criteria) this;
        }

        public Criteria andLimitNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("limit_num >=", value, "limitNum");
            return (Criteria) this;
        }

        public Criteria andLimitNumLessThan(Integer value) {
            addCriterion("limit_num <", value, "limitNum");
            return (Criteria) this;
        }

        public Criteria andLimitNumLessThanOrEqualTo(Integer value) {
            addCriterion("limit_num <=", value, "limitNum");
            return (Criteria) this;
        }

        public Criteria andLimitNumIn(List<Integer> values) {
            addCriterion("limit_num in", values, "limitNum");
            return (Criteria) this;
        }

        public Criteria andLimitNumNotIn(List<Integer> values) {
            addCriterion("limit_num not in", values, "limitNum");
            return (Criteria) this;
        }

        public Criteria andLimitNumBetween(Integer value1, Integer value2) {
            addCriterion("limit_num between", value1, value2, "limitNum");
            return (Criteria) this;
        }

        public Criteria andLimitNumNotBetween(Integer value1, Integer value2) {
            addCriterion("limit_num not between", value1, value2, "limitNum");
            return (Criteria) this;
        }

        public Criteria andUseDescIsNull() {
            addCriterion("use_desc is null");
            return (Criteria) this;
        }

        public Criteria andUseDescIsNotNull() {
            addCriterion("use_desc is not null");
            return (Criteria) this;
        }

        public Criteria andUseDescEqualTo(String value) {
            addCriterion("use_desc =", value, "useDesc");
            return (Criteria) this;
        }

        public Criteria andUseDescNotEqualTo(String value) {
            addCriterion("use_desc <>", value, "useDesc");
            return (Criteria) this;
        }

        public Criteria andUseDescGreaterThan(String value) {
            addCriterion("use_desc >", value, "useDesc");
            return (Criteria) this;
        }

        public Criteria andUseDescGreaterThanOrEqualTo(String value) {
            addCriterion("use_desc >=", value, "useDesc");
            return (Criteria) this;
        }

        public Criteria andUseDescLessThan(String value) {
            addCriterion("use_desc <", value, "useDesc");
            return (Criteria) this;
        }

        public Criteria andUseDescLessThanOrEqualTo(String value) {
            addCriterion("use_desc <=", value, "useDesc");
            return (Criteria) this;
        }

        public Criteria andUseDescLike(String value) {
            addCriterion("use_desc like", value, "useDesc");
            return (Criteria) this;
        }

        public Criteria andUseDescNotLike(String value) {
            addCriterion("use_desc not like", value, "useDesc");
            return (Criteria) this;
        }

        public Criteria andUseDescIn(List<String> values) {
            addCriterion("use_desc in", values, "useDesc");
            return (Criteria) this;
        }

        public Criteria andUseDescNotIn(List<String> values) {
            addCriterion("use_desc not in", values, "useDesc");
            return (Criteria) this;
        }

        public Criteria andUseDescBetween(String value1, String value2) {
            addCriterion("use_desc between", value1, value2, "useDesc");
            return (Criteria) this;
        }

        public Criteria andUseDescNotBetween(String value1, String value2) {
            addCriterion("use_desc not between", value1, value2, "useDesc");
            return (Criteria) this;
        }

        public Criteria andIsStopIsNull() {
            addCriterion("is_stop is null");
            return (Criteria) this;
        }

        public Criteria andIsStopIsNotNull() {
            addCriterion("is_stop is not null");
            return (Criteria) this;
        }

        public Criteria andIsStopEqualTo(Byte value) {
            addCriterion("is_stop =", value, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopNotEqualTo(Byte value) {
            addCriterion("is_stop <>", value, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopGreaterThan(Byte value) {
            addCriterion("is_stop >", value, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_stop >=", value, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopLessThan(Byte value) {
            addCriterion("is_stop <", value, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopLessThanOrEqualTo(Byte value) {
            addCriterion("is_stop <=", value, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopIn(List<Byte> values) {
            addCriterion("is_stop in", values, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopNotIn(List<Byte> values) {
            addCriterion("is_stop not in", values, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopBetween(Byte value1, Byte value2) {
            addCriterion("is_stop between", value1, value2, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopNotBetween(Byte value1, Byte value2) {
            addCriterion("is_stop not between", value1, value2, "isStop");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voucher
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voucher
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
