package com.lx.benefits.mapper.voucher;

import com.lx.benefits.bean.entity.voucher.employeeCreditVoucher;
import com.lx.benefits.bean.entity.voucher.employeeCreditVoucherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface employeeCreditVoucherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_credit_voucher
     *
     * @mbggenerated
     */
    int countByExample(employeeCreditVoucherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_credit_voucher
     *
     * @mbggenerated
     */
    int deleteByExample(employeeCreditVoucherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_credit_voucher
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_credit_voucher
     *
     * @mbggenerated
     */
    int insert(employeeCreditVoucher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_credit_voucher
     *
     * @mbggenerated
     */
    int insertSelective(employeeCreditVoucher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_credit_voucher
     *
     * @mbggenerated
     */
    List<employeeCreditVoucher> selectByExample(employeeCreditVoucherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_credit_voucher
     *
     * @mbggenerated
     */
    employeeCreditVoucher selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_credit_voucher
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") employeeCreditVoucher record,
                                 @Param("example") employeeCreditVoucherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_credit_voucher
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") employeeCreditVoucher record, @Param("example") employeeCreditVoucherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_credit_voucher
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(employeeCreditVoucher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_credit_voucher
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(employeeCreditVoucher record);
}
