package com.lx.benefits.mapper.voucher;

import com.lx.benefits.bean.entity.voucher.Voucher;
import com.lx.benefits.bean.entity.voucher.VoucherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoucherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    int countByExample(VoucherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    int deleteByExample(VoucherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long voucherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    int insert(Voucher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    int insertSelective(Voucher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    List<Voucher> selectByExample(VoucherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    Voucher selectByPrimaryKey(Long voucherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Voucher record, @Param("example") VoucherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Voucher record, @Param("example") VoucherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Voucher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voucher
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Voucher record);
}
