package com.lx.benefits.bean.entity.seckill;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Seckill implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_id
     *
     * @mbggenerated
     */
    private Long seckillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_name
     *
     * @mbggenerated
     */
    private String seckillName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.validate_start_time
     *
     * @mbggenerated
     */
    private Date validateStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.validate_end_time
     *
     * @mbggenerated
     */
    private Date validateEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.sku_id
     *
     * @mbggenerated
     */
    private Long skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_price
     *
     * @mbggenerated
     */
    private BigDecimal seckillPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_storage
     *
     * @mbggenerated
     */
    private Integer seckillStorage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.limit_per_user
     *
     * @mbggenerated
     */
    private Integer limitPerUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.order_cancel_time
     *
     * @mbggenerated
     */
    private Integer orderCancelTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.already_buy
     *
     * @mbggenerated
     */
    private Integer alreadyBuy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    private Integer isStop;

    private String startTime;

    private String endTime;

    private String goodsName;

    private Integer leftStorage;


    public Integer getLeftStorage() {
        return leftStorage;
    }

    public void setLeftStorage(Integer leftStorage) {
        this.leftStorage = leftStorage;
    }

    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public Integer getIsStop() {
        return isStop;
    }

    public void setIsStop(Integer isStop) {
        this.isStop = isStop;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seckill
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_id
     *
     * @return the value of seckill.seckill_id
     *
     * @mbggenerated
     */
    public Long getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_id
     *
     * @param seckillId the value for seckill.seckill_id
     *
     * @mbggenerated
     */
    public void setSeckillId(Long seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_name
     *
     * @return the value of seckill.seckill_name
     *
     * @mbggenerated
     */
    public String getSeckillName() {
        return seckillName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_name
     *
     * @param seckillName the value for seckill.seckill_name
     *
     * @mbggenerated
     */
    public void setSeckillName(String seckillName) {
        this.seckillName = seckillName == null ? null : seckillName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.validate_start_time
     *
     * @return the value of seckill.validate_start_time
     *
     * @mbggenerated
     */
    public Date getValidateStartTime() {
        return validateStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.validate_start_time
     *
     * @param validateStartTime the value for seckill.validate_start_time
     *
     * @mbggenerated
     */
    public void setValidateStartTime(Date validateStartTime) {
        this.validateStartTime = validateStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.validate_end_time
     *
     * @return the value of seckill.validate_end_time
     *
     * @mbggenerated
     */
    public Date getValidateEndTime() {
        return validateEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.validate_end_time
     *
     * @param validateEndTime the value for seckill.validate_end_time
     *
     * @mbggenerated
     */
    public void setValidateEndTime(Date validateEndTime) {
        this.validateEndTime = validateEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.sku_id
     *
     * @return the value of seckill.sku_id
     *
     * @mbggenerated
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.sku_id
     *
     * @param skuId the value for seckill.sku_id
     *
     * @mbggenerated
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_price
     *
     * @return the value of seckill.seckill_price
     *
     * @mbggenerated
     */
    public BigDecimal getSeckillPrice() {
        return seckillPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_price
     *
     * @param seckillPrice the value for seckill.seckill_price
     *
     * @mbggenerated
     */
    public void setSeckillPrice(BigDecimal seckillPrice) {
        this.seckillPrice = seckillPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_storage
     *
     * @return the value of seckill.seckill_storage
     *
     * @mbggenerated
     */
    public Integer getSeckillStorage() {
        return seckillStorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_storage
     *
     * @param seckillStorage the value for seckill.seckill_storage
     *
     * @mbggenerated
     */
    public void setSeckillStorage(Integer seckillStorage) {
        this.seckillStorage = seckillStorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.limit_per_user
     *
     * @return the value of seckill.limit_per_user
     *
     * @mbggenerated
     */
    public Integer getLimitPerUser() {
        return limitPerUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.limit_per_user
     *
     * @param limitPerUser the value for seckill.limit_per_user
     *
     * @mbggenerated
     */
    public void setLimitPerUser(Integer limitPerUser) {
        this.limitPerUser = limitPerUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.order_cancel_time
     *
     * @return the value of seckill.order_cancel_time
     *
     * @mbggenerated
     */
    public Integer getOrderCancelTime() {
        return orderCancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.order_cancel_time
     *
     * @param orderCancelTime the value for seckill.order_cancel_time
     *
     * @mbggenerated
     */
    public void setOrderCancelTime(Integer orderCancelTime) {
        this.orderCancelTime = orderCancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.already_buy
     *
     * @return the value of seckill.already_buy
     *
     * @mbggenerated
     */
    public Integer getAlreadyBuy() {
        return alreadyBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.already_buy
     *
     * @param alreadyBuy the value for seckill.already_buy
     *
     * @mbggenerated
     */
    public void setAlreadyBuy(Integer alreadyBuy) {
        this.alreadyBuy = alreadyBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.status
     *
     * @return the value of seckill.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.status
     *
     * @param status the value for seckill.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.create_time
     *
     * @return the value of seckill.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.create_time
     *
     * @param createTime the value for seckill.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.update_time
     *
     * @return the value of seckill.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.update_time
     *
     * @param updateTime the value for seckill.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Seckill other = (Seckill) that;
        return (this.getSeckillId() == null ? other.getSeckillId() == null : this.getSeckillId().equals(other.getSeckillId()))
            && (this.getSeckillName() == null ? other.getSeckillName() == null : this.getSeckillName().equals(other.getSeckillName()))
            && (this.getValidateStartTime() == null ? other.getValidateStartTime() == null : this.getValidateStartTime().equals(other.getValidateStartTime()))
            && (this.getValidateEndTime() == null ? other.getValidateEndTime() == null : this.getValidateEndTime().equals(other.getValidateEndTime()))
            && (this.getSkuId() == null ? other.getSkuId() == null : this.getSkuId().equals(other.getSkuId()))
            && (this.getSeckillPrice() == null ? other.getSeckillPrice() == null : this.getSeckillPrice().equals(other.getSeckillPrice()))
            && (this.getSeckillStorage() == null ? other.getSeckillStorage() == null : this.getSeckillStorage().equals(other.getSeckillStorage()))
            && (this.getLimitPerUser() == null ? other.getLimitPerUser() == null : this.getLimitPerUser().equals(other.getLimitPerUser()))
            && (this.getOrderCancelTime() == null ? other.getOrderCancelTime() == null : this.getOrderCancelTime().equals(other.getOrderCancelTime()))
            && (this.getAlreadyBuy() == null ? other.getAlreadyBuy() == null : this.getAlreadyBuy().equals(other.getAlreadyBuy()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSeckillId() == null) ? 0 : getSeckillId().hashCode());
        result = prime * result + ((getSeckillName() == null) ? 0 : getSeckillName().hashCode());
        result = prime * result + ((getValidateStartTime() == null) ? 0 : getValidateStartTime().hashCode());
        result = prime * result + ((getValidateEndTime() == null) ? 0 : getValidateEndTime().hashCode());
        result = prime * result + ((getSkuId() == null) ? 0 : getSkuId().hashCode());
        result = prime * result + ((getSeckillPrice() == null) ? 0 : getSeckillPrice().hashCode());
        result = prime * result + ((getSeckillStorage() == null) ? 0 : getSeckillStorage().hashCode());
        result = prime * result + ((getLimitPerUser() == null) ? 0 : getLimitPerUser().hashCode());
        result = prime * result + ((getOrderCancelTime() == null) ? 0 : getOrderCancelTime().hashCode());
        result = prime * result + ((getAlreadyBuy() == null) ? 0 : getAlreadyBuy().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seckillId=").append(seckillId);
        sb.append(", seckillName=").append(seckillName);
        sb.append(", validateStartTime=").append(validateStartTime);
        sb.append(", validateEndTime=").append(validateEndTime);
        sb.append(", skuId=").append(skuId);
        sb.append(", seckillPrice=").append(seckillPrice);
        sb.append(", seckillStorage=").append(seckillStorage);
        sb.append(", limitPerUser=").append(limitPerUser);
        sb.append(", orderCancelTime=").append(orderCancelTime);
        sb.append(", alreadyBuy=").append(alreadyBuy);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
