package com.lx.benefits.bean.entity.seckill;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SeckillExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seckill
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seckill
     *
     * @mbggenerated
     */
    protected boolean distinct;

    private Integer offset;

    private Integer limit;


    public Integer getOffset() {
        return offset;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seckill
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated
     */
    public SeckillExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table seckill
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeckillIdIsNull() {
            addCriterion("seckill_id is null");
            return (Criteria) this;
        }

        public Criteria andSeckillIdIsNotNull() {
            addCriterion("seckill_id is not null");
            return (Criteria) this;
        }

        public Criteria andSeckillIdEqualTo(Long value) {
            addCriterion("seckill_id =", value, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdNotEqualTo(Long value) {
            addCriterion("seckill_id <>", value, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdGreaterThan(Long value) {
            addCriterion("seckill_id >", value, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdGreaterThanOrEqualTo(Long value) {
            addCriterion("seckill_id >=", value, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdLessThan(Long value) {
            addCriterion("seckill_id <", value, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdLessThanOrEqualTo(Long value) {
            addCriterion("seckill_id <=", value, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdIn(List<Long> values) {
            addCriterion("seckill_id in", values, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdNotIn(List<Long> values) {
            addCriterion("seckill_id not in", values, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdBetween(Long value1, Long value2) {
            addCriterion("seckill_id between", value1, value2, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillIdNotBetween(Long value1, Long value2) {
            addCriterion("seckill_id not between", value1, value2, "seckillId");
            return (Criteria) this;
        }

        public Criteria andSeckillNameIsNull() {
            addCriterion("seckill_name is null");
            return (Criteria) this;
        }

        public Criteria andSeckillNameIsNotNull() {
            addCriterion("seckill_name is not null");
            return (Criteria) this;
        }

        public Criteria andSeckillNameEqualTo(String value) {
            addCriterion("seckill_name =", value, "seckillName");
            return (Criteria) this;
        }

        public Criteria andSeckillNameNotEqualTo(String value) {
            addCriterion("seckill_name <>", value, "seckillName");
            return (Criteria) this;
        }

        public Criteria andSeckillNameGreaterThan(String value) {
            addCriterion("seckill_name >", value, "seckillName");
            return (Criteria) this;
        }

        public Criteria andSeckillNameGreaterThanOrEqualTo(String value) {
            addCriterion("seckill_name >=", value, "seckillName");
            return (Criteria) this;
        }

        public Criteria andSeckillNameLessThan(String value) {
            addCriterion("seckill_name <", value, "seckillName");
            return (Criteria) this;
        }

        public Criteria andSeckillNameLessThanOrEqualTo(String value) {
            addCriterion("seckill_name <=", value, "seckillName");
            return (Criteria) this;
        }

        public Criteria andSeckillNameLike(String value) {
            addCriterion("seckill_name like", value, "seckillName");
            return (Criteria) this;
        }

        public Criteria andSeckillNameNotLike(String value) {
            addCriterion("seckill_name not like", value, "seckillName");
            return (Criteria) this;
        }

        public Criteria andSeckillNameIn(List<String> values) {
            addCriterion("seckill_name in", values, "seckillName");
            return (Criteria) this;
        }

        public Criteria andSeckillNameNotIn(List<String> values) {
            addCriterion("seckill_name not in", values, "seckillName");
            return (Criteria) this;
        }

        public Criteria andSeckillNameBetween(String value1, String value2) {
            addCriterion("seckill_name between", value1, value2, "seckillName");
            return (Criteria) this;
        }

        public Criteria andSeckillNameNotBetween(String value1, String value2) {
            addCriterion("seckill_name not between", value1, value2, "seckillName");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeIsNull() {
            addCriterion("validate_start_time is null");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeIsNotNull() {
            addCriterion("validate_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeEqualTo(Date value) {
            addCriterion("validate_start_time =", value, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeNotEqualTo(Date value) {
            addCriterion("validate_start_time <>", value, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeGreaterThan(Date value) {
            addCriterion("validate_start_time >", value, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("validate_start_time >=", value, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeLessThan(Date value) {
            addCriterion("validate_start_time <", value, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("validate_start_time <=", value, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeIn(List<Date> values) {
            addCriterion("validate_start_time in", values, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeNotIn(List<Date> values) {
            addCriterion("validate_start_time not in", values, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeBetween(Date value1, Date value2) {
            addCriterion("validate_start_time between", value1, value2, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("validate_start_time not between", value1, value2, "validateStartTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeIsNull() {
            addCriterion("validate_end_time is null");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeIsNotNull() {
            addCriterion("validate_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeEqualTo(Date value) {
            addCriterion("validate_end_time =", value, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeNotEqualTo(Date value) {
            addCriterion("validate_end_time <>", value, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeGreaterThan(Date value) {
            addCriterion("validate_end_time >", value, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("validate_end_time >=", value, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeLessThan(Date value) {
            addCriterion("validate_end_time <", value, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("validate_end_time <=", value, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeIn(List<Date> values) {
            addCriterion("validate_end_time in", values, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeNotIn(List<Date> values) {
            addCriterion("validate_end_time not in", values, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeBetween(Date value1, Date value2) {
            addCriterion("validate_end_time between", value1, value2, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andValidateEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("validate_end_time not between", value1, value2, "validateEndTime");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNull() {
            addCriterion("sku_id is null");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNotNull() {
            addCriterion("sku_id is not null");
            return (Criteria) this;
        }

        public Criteria andSkuIdEqualTo(Long value) {
            addCriterion("sku_id =", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotEqualTo(Long value) {
            addCriterion("sku_id <>", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThan(Long value) {
            addCriterion("sku_id >", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sku_id >=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThan(Long value) {
            addCriterion("sku_id <", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThanOrEqualTo(Long value) {
            addCriterion("sku_id <=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIn(List<Long> values) {
            addCriterion("sku_id in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotIn(List<Long> values) {
            addCriterion("sku_id not in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdBetween(Long value1, Long value2) {
            addCriterion("sku_id between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotBetween(Long value1, Long value2) {
            addCriterion("sku_id not between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSeckillPriceIsNull() {
            addCriterion("seckill_price is null");
            return (Criteria) this;
        }

        public Criteria andSeckillPriceIsNotNull() {
            addCriterion("seckill_price is not null");
            return (Criteria) this;
        }

        public Criteria andSeckillPriceEqualTo(BigDecimal value) {
            addCriterion("seckill_price =", value, "seckillPrice");
            return (Criteria) this;
        }

        public Criteria andSeckillPriceNotEqualTo(BigDecimal value) {
            addCriterion("seckill_price <>", value, "seckillPrice");
            return (Criteria) this;
        }

        public Criteria andSeckillPriceGreaterThan(BigDecimal value) {
            addCriterion("seckill_price >", value, "seckillPrice");
            return (Criteria) this;
        }

        public Criteria andSeckillPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("seckill_price >=", value, "seckillPrice");
            return (Criteria) this;
        }

        public Criteria andSeckillPriceLessThan(BigDecimal value) {
            addCriterion("seckill_price <", value, "seckillPrice");
            return (Criteria) this;
        }

        public Criteria andSeckillPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("seckill_price <=", value, "seckillPrice");
            return (Criteria) this;
        }

        public Criteria andSeckillPriceIn(List<BigDecimal> values) {
            addCriterion("seckill_price in", values, "seckillPrice");
            return (Criteria) this;
        }

        public Criteria andSeckillPriceNotIn(List<BigDecimal> values) {
            addCriterion("seckill_price not in", values, "seckillPrice");
            return (Criteria) this;
        }

        public Criteria andSeckillPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("seckill_price between", value1, value2, "seckillPrice");
            return (Criteria) this;
        }

        public Criteria andSeckillPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("seckill_price not between", value1, value2, "seckillPrice");
            return (Criteria) this;
        }

        public Criteria andSeckillStorageIsNull() {
            addCriterion("seckill_storage is null");
            return (Criteria) this;
        }

        public Criteria andSeckillStorageIsNotNull() {
            addCriterion("seckill_storage is not null");
            return (Criteria) this;
        }

        public Criteria andSeckillStorageEqualTo(Integer value) {
            addCriterion("seckill_storage =", value, "seckillStorage");
            return (Criteria) this;
        }

        public Criteria andSeckillStorageNotEqualTo(Integer value) {
            addCriterion("seckill_storage <>", value, "seckillStorage");
            return (Criteria) this;
        }

        public Criteria andSeckillStorageGreaterThan(Integer value) {
            addCriterion("seckill_storage >", value, "seckillStorage");
            return (Criteria) this;
        }

        public Criteria andSeckillStorageGreaterThanOrEqualTo(Integer value) {
            addCriterion("seckill_storage >=", value, "seckillStorage");
            return (Criteria) this;
        }

        public Criteria andSeckillStorageLessThan(Integer value) {
            addCriterion("seckill_storage <", value, "seckillStorage");
            return (Criteria) this;
        }

        public Criteria andSeckillStorageLessThanOrEqualTo(Integer value) {
            addCriterion("seckill_storage <=", value, "seckillStorage");
            return (Criteria) this;
        }

        public Criteria andSeckillStorageIn(List<Integer> values) {
            addCriterion("seckill_storage in", values, "seckillStorage");
            return (Criteria) this;
        }

        public Criteria andSeckillStorageNotIn(List<Integer> values) {
            addCriterion("seckill_storage not in", values, "seckillStorage");
            return (Criteria) this;
        }

        public Criteria andSeckillStorageBetween(Integer value1, Integer value2) {
            addCriterion("seckill_storage between", value1, value2, "seckillStorage");
            return (Criteria) this;
        }

        public Criteria andSeckillStorageNotBetween(Integer value1, Integer value2) {
            addCriterion("seckill_storage not between", value1, value2, "seckillStorage");
            return (Criteria) this;
        }

        public Criteria andLimitPerUserIsNull() {
            addCriterion("limit_per_user is null");
            return (Criteria) this;
        }

        public Criteria andLimitPerUserIsNotNull() {
            addCriterion("limit_per_user is not null");
            return (Criteria) this;
        }

        public Criteria andLimitPerUserEqualTo(Integer value) {
            addCriterion("limit_per_user =", value, "limitPerUser");
            return (Criteria) this;
        }

        public Criteria andLimitPerUserNotEqualTo(Integer value) {
            addCriterion("limit_per_user <>", value, "limitPerUser");
            return (Criteria) this;
        }

        public Criteria andLimitPerUserGreaterThan(Integer value) {
            addCriterion("limit_per_user >", value, "limitPerUser");
            return (Criteria) this;
        }

        public Criteria andLimitPerUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("limit_per_user >=", value, "limitPerUser");
            return (Criteria) this;
        }

        public Criteria andLimitPerUserLessThan(Integer value) {
            addCriterion("limit_per_user <", value, "limitPerUser");
            return (Criteria) this;
        }

        public Criteria andLimitPerUserLessThanOrEqualTo(Integer value) {
            addCriterion("limit_per_user <=", value, "limitPerUser");
            return (Criteria) this;
        }

        public Criteria andLimitPerUserIn(List<Integer> values) {
            addCriterion("limit_per_user in", values, "limitPerUser");
            return (Criteria) this;
        }

        public Criteria andLimitPerUserNotIn(List<Integer> values) {
            addCriterion("limit_per_user not in", values, "limitPerUser");
            return (Criteria) this;
        }

        public Criteria andLimitPerUserBetween(Integer value1, Integer value2) {
            addCriterion("limit_per_user between", value1, value2, "limitPerUser");
            return (Criteria) this;
        }

        public Criteria andLimitPerUserNotBetween(Integer value1, Integer value2) {
            addCriterion("limit_per_user not between", value1, value2, "limitPerUser");
            return (Criteria) this;
        }

        public Criteria andOrderCancelTimeIsNull() {
            addCriterion("order_cancel_time is null");
            return (Criteria) this;
        }

        public Criteria andOrderCancelTimeIsNotNull() {
            addCriterion("order_cancel_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrderCancelTimeEqualTo(Integer value) {
            addCriterion("order_cancel_time =", value, "orderCancelTime");
            return (Criteria) this;
        }

        public Criteria andOrderCancelTimeNotEqualTo(Integer value) {
            addCriterion("order_cancel_time <>", value, "orderCancelTime");
            return (Criteria) this;
        }

        public Criteria andOrderCancelTimeGreaterThan(Integer value) {
            addCriterion("order_cancel_time >", value, "orderCancelTime");
            return (Criteria) this;
        }

        public Criteria andOrderCancelTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_cancel_time >=", value, "orderCancelTime");
            return (Criteria) this;
        }

        public Criteria andOrderCancelTimeLessThan(Integer value) {
            addCriterion("order_cancel_time <", value, "orderCancelTime");
            return (Criteria) this;
        }

        public Criteria andOrderCancelTimeLessThanOrEqualTo(Integer value) {
            addCriterion("order_cancel_time <=", value, "orderCancelTime");
            return (Criteria) this;
        }

        public Criteria andOrderCancelTimeIn(List<Integer> values) {
            addCriterion("order_cancel_time in", values, "orderCancelTime");
            return (Criteria) this;
        }

        public Criteria andOrderCancelTimeNotIn(List<Integer> values) {
            addCriterion("order_cancel_time not in", values, "orderCancelTime");
            return (Criteria) this;
        }

        public Criteria andOrderCancelTimeBetween(Integer value1, Integer value2) {
            addCriterion("order_cancel_time between", value1, value2, "orderCancelTime");
            return (Criteria) this;
        }

        public Criteria andOrderCancelTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("order_cancel_time not between", value1, value2, "orderCancelTime");
            return (Criteria) this;
        }

        public Criteria andAlreadyBuyIsNull() {
            addCriterion("already_buy is null");
            return (Criteria) this;
        }

        public Criteria andAlreadyBuyIsNotNull() {
            addCriterion("already_buy is not null");
            return (Criteria) this;
        }

        public Criteria andAlreadyBuyEqualTo(Integer value) {
            addCriterion("already_buy =", value, "alreadyBuy");
            return (Criteria) this;
        }

        public Criteria andAlreadyBuyNotEqualTo(Integer value) {
            addCriterion("already_buy <>", value, "alreadyBuy");
            return (Criteria) this;
        }

        public Criteria andAlreadyBuyGreaterThan(Integer value) {
            addCriterion("already_buy >", value, "alreadyBuy");
            return (Criteria) this;
        }

        public Criteria andAlreadyBuyGreaterThanOrEqualTo(Integer value) {
            addCriterion("already_buy >=", value, "alreadyBuy");
            return (Criteria) this;
        }

        public Criteria andAlreadyBuyLessThan(Integer value) {
            addCriterion("already_buy <", value, "alreadyBuy");
            return (Criteria) this;
        }

        public Criteria andAlreadyBuyLessThanOrEqualTo(Integer value) {
            addCriterion("already_buy <=", value, "alreadyBuy");
            return (Criteria) this;
        }

        public Criteria andAlreadyBuyIn(List<Integer> values) {
            addCriterion("already_buy in", values, "alreadyBuy");
            return (Criteria) this;
        }

        public Criteria andAlreadyBuyNotIn(List<Integer> values) {
            addCriterion("already_buy not in", values, "alreadyBuy");
            return (Criteria) this;
        }

        public Criteria andAlreadyBuyBetween(Integer value1, Integer value2) {
            addCriterion("already_buy between", value1, value2, "alreadyBuy");
            return (Criteria) this;
        }

        public Criteria andAlreadyBuyNotBetween(Integer value1, Integer value2) {
            addCriterion("already_buy not between", value1, value2, "alreadyBuy");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table seckill
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table seckill
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
