package com.lx.benefits.mapper.agent;

import java.util.List;

import com.lx.benefits.bean.entity.agent.AgentRebateDeploy;
import com.lx.benefits.bean.entity.agent.AgentRebateDeployExample;
import org.apache.ibatis.annotations.Param;

public interface AgentRebateDeployMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    int countByExample(AgentRebateDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    int deleteByExample(AgentRebateDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    int insert(AgentRebateDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    int insertSelective(AgentRebateDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    List<AgentRebateDeploy> selectByExample(AgentRebateDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    AgentRebateDeploy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AgentRebateDeploy record, @Param("example") AgentRebateDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AgentRebateDeploy record, @Param("example") AgentRebateDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AgentRebateDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_rebate_deploy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AgentRebateDeploy record);
}
